.coveragerc
.travis.yml
chainladder/tests/test_chainladder.py
test_chainladder.py

Hello,
I took a shot at re-writing the travis script so that you can run all the tests you've built. Might also be nice to add coverage. If this works, I'll add that. 
I should mention there are a few caveats:
* nlopt seems broken. I'm not exactly sure how to install it but there's lots of recent issues getting it to work. I *think* this approach works, but its probably not ideal. 
* I have to install `rpy2` and then download, compile, install all of R `ChainLadders` dependents--of which there are many. It would be much, much faster if we could just extract those cause over 12 minutes of the build time is building all the R stuff which is useless. 
* We might want to discuss which versions of numpy/pandas you want to build against. Since this is a new package, I guess we can be somewhat …

TST: Rework .travis.yml to run tests

---

chainladder/core/display.py
chainladder/core/pandas.py

Reference to #92  - added a first attempt.
Saddly I'm working on windows where rpy2 doesn't work so haven't been able to run Pytest. Will make a Docker image for this soon, but for now relying on github Action which passed.

to_frame() with origin as datetime 

---

chainladder/tails/curve.py

Created a reg_threshold tuple to set lower and upper thresholds for the log regression used in the curve fit. See issue #113 for more details.

Solution for issue #113

---

docs/tutorials/deterministic-tutorial.ipynb
docs/tutorials/development-tutorial.ipynb
docs/tutorials/triangle-tutorial.ipynb

Good morning @jbogaardt I was revisiting the Tutorials and noticed a few basic typos that may be of some minor assistance

Some basic tutorial typos

---

.gitignore
docs/contributing.rst

- Included code to fix missing dependencies
- Fixed some visual stuff (capitalize titles, lined up bullet points, etc)

Revised the "Contributing" Section 

---

docs/contributing.rst
docs/install.rst

Added flag on channel_priority so conda doesn't get stuck when updating packages
Added s new section on how packages can be updated

Improved the Installation Page

---

chainladder/development/base.py
chainladder/development/development.py

Tried some examples, they all work. Let me know if you see anything weird.
```python
import pandas as pd
import numpy as np
import chainladder as cl
raa_df = pd.read_csv(
"https://raw.githubusercontent.com/casact/chainladder-python/master/chainladder/utils/data/raa.csv"
)
raa = cl.Triangle(raa_df, origin="origin", development="development", columns="values")
raa.link_ratio.heatmap()
cl.Development(drop_high=0).fit(raa).cdf_
cl.Development(drop_high=0).fit(raa).cdf_
cl.Development(drop_high=[True, False, True, False]).fit(raa).cdf_
cl.Development(drop_high=[2, 3, 3, 3], drop_low=[0, 1, 0], preserve=2).fit(raa).cdf_
```

Improved the drop_high and drop_low, introduced preserve attribute in chainladder.Development(...)

---

chainladder/core/display.py
chainladder/core/pandas.py
chainladder/core/triangle.py

Address #248, and suppressed warnings for dependent functions that call to_frame()

Fixed origin_as_datetime bug in to_frame() and suppressed warnings #268, Support "H" and "S" for origin_grain, and better formatting per #99

---

chainladder/development/outstanding.py
chainladder/development/tests/test_outstanding.py

Addressed #283.
Test code:
```python
import chainladder as cl
import numpy as np
usauto = cl.load_sample("usauto")
model = cl.CaseOutstanding(
paid_to_incurred=("paid", "incurred"), paid_n_periods=3, case_n_periods=3
).fit(usauto)
expected_paid_ldf = np.array(
[[0.833, 0.701, 0.714, 0.714, 0.653, 0.631, 0.553, 0.437, 0.524,]]
)
assert (
model.paid_ldf_.to_frame(origin_as_datetime=False).values - expected_paid_ldf
< 0.001
).all()
expected_case_ldf = np.array(
[[0.526, 0.566, 0.528, 0.486, 0.511, 0.555, 0.652, 0.674, 0.580,]]
)
assert (
model.case_ldf_.to_frame(origin_as_datetime=False).values - expected_case_ldf
< 0.001
).all()
```

Addressed 283

---

chainladder/development/base.py
chainladder/development/development.py
chainladder/development/tests/test_development.py

293 n periods and drophighlow behavior

---

chainladder/development/development.py

Adding std_residuals_ to the transformer

---

docs/_config.yml
docs/_toc.yml
docs/guides_intro.md
docs/intro.md
docs/library/references.bib
docs/library/usage.md
docs/tutorials/demo-blank.ipynb
docs/tutorials/demo.ipynb

I think I might have broke the [references page](https://chainladder-python.readthedocs.io/en/latest/library/references.html), but not sure how to fix it. @jbogaardt can you take a look?

Annual meeting prep

---

chainladder/methods/benktander.py
chainladder/methods/capecod.py

Addressed #321, problem was in the `trend_array` near [line 159](https://github.com/casact/chainladder-python/blob/master/chainladder/methods/capecod.py#L159).

addressed #321

---

chainladder/development/base.py

removed for loop. changed all 2D references to 4D. 
note: this was only done for _drop_n. similar work needs to be done for _drop_x

Adding 4D support to drop_hi/lo

---

chainladder/utils/tests/test_utilities.py

Addressing the assert from #368

Corrected number of days in a year to 365.25

---

chainladder/development/base.py

plus some further debugging of drop_hi/lo

adding 4D support for drop_above/below

---

chainladder/development/incremental.py

Improvement for easier inspection during analysis
pass the test below
```python
genins = cl.load_sample("genins")
genins_dev = cl.Development().fit_transform(genins)
genins_cl = cl.Chainladder().fit(genins_dev)
genins_incr = cl.IncrementalAdditive(average = "simple", n_periods = 4).fit_transform(genins, sample_weight = genins_cl.ultimate_ * 5)
print(genins_incr.w_)
print(genins_incr.zeta_)
print(genins_incr.cum_zeta_)
print(genins_incr.fit_zeta_)
print(genins_incr.sample_weight)
print(genins_incr.tri_zeta)
```

QoL improvement

---

chainladder/development/base.py

this commit introduces a revamped set of drop functions, in order to allow both multiplicative and additive development classes to get the appropriate drop weight triangle. new functions are added with an _func suffix. due to the magnitude of this change I'm adding these revamp functions in parallel in order to enable full testing, rather than overwriting existing drop functions.
at a high level, the function _set_weight_func is the consolidated wrapper for all Development subclasses to call. This function combines the previous _assign_n_period_weight and _drop_adjustment. it also directly takes the factor triangle, which gets rid of ambiguity with multiplicative vs additive factor sizes (multiplicative factors have one fewer row and one fewer column). 
details:
- _drop and …

revamping drop functions

---

chainladder/development/tests/test_development.py

not sure if i'm doing it right.
requires #387

adding some tests for the revamped drop function

---

chainladder/development/tests/test_incremental.py

Adding test wth CL and BF

---

chainladder/development/base.py
chainladder/development/tests/test_development.py

resubmitting #389 and #390 as a single pull request

Henrydingliu enhancement 1 2022 11 29

---

chainladder/Test.py
chainladder/development/base.py
chainladder/development/development.py
chainladder/development/incremental.py
chainladder/development/tests/test_development.py
chainladder/development/tests/test_incremental.py

Development
-output _set_weight_func to w_v2;
-enable pipeline for w_v2
-add test for both
Incremental
-changed over to _set_weight_func
-enable pipeline
-add test

w_v2_ and pipeline in Development

---

chainladder/development/base.py
chainladder/development/development.py
chainladder/development/incremental.py
chainladder/development/tests/test_development.py
chainladder/development/tests/test_incremental.py

adding w_v2_ in development to further beta _set_weight_func. also adding pipeline support for w_v2_ as well
switching incremental to using _set_weight_func with pipeline support
tests added for both

next step for #376

---

chainladder/development/base.py
chainladder/development/incremental.py

start of some consolidation/standardization effort between Development and IncrementalAdditive, with the eventual goal of generalizing tails and BF that handles additive factors.

consolidating weighted regression factor fit

---

chainladder/adjustments/bootstrap.py
chainladder/development/base.py
chainladder/development/clark.py
chainladder/tails/bondy.py
chainladder/tails/clark.py
chainladder/tails/curve.py
chainladder/utils/utility_functions.py

Expanded mappings to include semester sampling

---

chainladder/development/learning.py

was going to submit similar to pull request #403 but got beaten to it. seemed to be missing one more file still

fix one more ref to semiannual

---

chainladder/tails/curve.py
chainladder/tails/tests/test_exponential.py

TailCurve argument validation

---

docs/tutorials/demo-blank.ipynb

Better blanks to fill in. And some notes clean up.

Cas webinar

---

requirements.txt

As discussed in https://github.com/casact/chainladder-python/issues/438, there are currently breaking changes with Pandas 2.0.

add max version of pandas in requirements.txt

---

docs/_toc.yml
docs/conf.py
docs/gallery/index.md
docs/getting_started/online_sandbox/demo-blank-concurrent.ipynb
docs/getting_started/online_sandbox/sandbox_intro.md
docs/intro.md

- Added online sandbox page
- Better icons for some of the chapters :)

Improved Docs

---

chainladder/methods/tests/test_predict.py

prepend test_ to test functions

---

chainladder/core/base.py
chainladder/utils/weighted_regression.py

- Fixed #510 
- And warnings from nans: https://github.com/genedan/reserving-paper/issues/9

Suppress warnings
